### ISSUE TITLE
OpenSCAD

### ISSUE THREAD

**Issue by KirillTemnov** [soda-without-bekerman/Hacks-and-Tips#136]
Обновить справку:
- примеры для всех операторов/функций
- картинки для всех примеров
- фигуры
  - `circle`
  - `square`
  - `polygon`
  - `polyhedron`
- операции и преобразования
  - `hull`
  - `mirror`
  - `minkowski`
  - `union`
  - `intersection`
  - `import`
  - `linear_extrude`
  - `rotate_extrude`
- исправить цилинд**e**р -> цилиндр

**Comment by MaximLoguncov** [comment]
@BogdanNemirovich напиши подробно. Что не так?
